//
//  TemporaryData.swift
//  ChatApp
//
//  Created by Александр Саушев on 03.10.2020.
//  Copyright © 2020 Александр Саушев. All rights reserved.
//

import Foundation

func dateFormatter(_ dateString: String) -> Date {
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy/MM/dd HH:mm"
    guard let date = formatter.date(from: dateString) else { return Date() }
    return date
}

var conversationsListExample: [ConversationCellModel] = [
    ConversationCellModel(name: "Дмитрий",
                          message: "An suas viderer pro. Vis cu magna altera, ex his vivendo atomorum.",
                          date: dateFormatter("2020/09/30 00:31"),
                          isOnline: true,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Станислав",
                          message: "Reprehenderit mollit excepteur labore deserunt officia laboris eiusmod cillum eu duis",
                          date: dateFormatter("2020/09/30 00:31"),
                          isOnline: true,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Антон",
                          message: "Amet enim do laborum tempor nisi aliqua ad adipisicing.",
                          date: Date(),
                          isOnline: true,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Виктория",
                          message: "Voluptate irure aliquip consectetur commodo ex ex.",
                          date: Date(),
                          isOnline: true,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Роман",
                          message: "",
                          date: dateFormatter("2020/09/27 00:31"),
                          isOnline: true,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Алексей",
                          message: "",
                          date: dateFormatter("2020/09/28 00:31"),
                          isOnline: true,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Анна",
                          message: "",
                          date: Date(),
                          isOnline: true,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Артур",
                          message: "",
                          date: Date(),
                          isOnline: true,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Александр",
                          message: "An suas viderer pro. Vis cu magna altera, ex his vivendo atomorum.",
                          date: dateFormatter("2020/09/21 00:31"),
                          isOnline: true,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Никита",
                          message: "Reprehenderit mollit excepteur labore deserunt officia laboris eiusmod cillum eu duis",
                          date: dateFormatter("2020/08/25 00:31"),
                          isOnline: true,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Марат",
                          message: "Aliqua mollit nisi incididunt id eu consequat eu cupidatat.",
                          date: dateFormatter("2020/09/29 00:31"),
                          isOnline: false,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Данила",
                          message: "Voluptate irure aliquip consectetur commodo ex ex.",
                          date: dateFormatter("2020/09/29 00:31"),
                          isOnline: false,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Егор",
                          message: "Ex Lorem veniam veniam irure sunt adipisicing culpa.",
                          date: Date(),
                          isOnline: false,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Дмитрий",
                          message: "Dolore veniam Lorem occaecat veniam irure laborum est amet.",
                          date: Date(),
                          isOnline: false,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Наталья",
                          message: "",
                          date: dateFormatter("2020/07/25 00:31"),
                          isOnline: false,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Александра",
                          message: "",
                          date: dateFormatter("2020/06/25 00:31"),
                          isOnline: false,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Владимир",
                          message: "",
                          date: Date(),
                          isOnline: false,
                          hasUnreadMessages: true),
    ConversationCellModel(name: "Алексей",
                          message: "",
                          date: Date(),
                          isOnline: false,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Никита",
                          message: "An suas viderer pro. Vis cu magna altera, ex his vivendo atomorum.",
                          date: dateFormatter("2020/05/25 00:31"),
                          isOnline: false,
                          hasUnreadMessages: false),
    ConversationCellModel(name: "Владислав",
                          message: "Aliqua mollit nisi incididunt id eu consequat eu cupidatat.",
                          date: dateFormatter("2020/03/25 00:31"),
                          isOnline: false,
                          hasUnreadMessages: true)
]

var messageExample: [MessageCellModel] = [
    MessageCellModel(text: "Good Morning!", isIncoming: false),
    MessageCellModel(text: "Japan looks amazing!", isIncoming: false),
    MessageCellModel(text: "Do you know what time is it?", isIncoming: true),
    MessageCellModel(text: "It's morning in Tokyo 😎", isIncoming: false),
    MessageCellModel(text: "What is the most popular meal in Japan?", isIncoming: true),
    MessageCellModel(text: "Do you like it?", isIncoming: true),
    MessageCellModel(text: "I like it", isIncoming: false),
    MessageCellModel(text: "I will write you", isIncoming: false),
    MessageCellModel(text: "Ok, see you", isIncoming: true),
    MessageCellModel(text: "Have a nice day", isIncoming: true),
    MessageCellModel(text: "И еще", isIncoming: false),
    MessageCellModel(text: "несколько", isIncoming: false),
    MessageCellModel(text: "сообщений,", isIncoming: false),
    MessageCellModel(text: "чтобы", isIncoming: true),
    MessageCellModel(text: "проверить", isIncoming: true),
    MessageCellModel(text: "скролл", isIncoming: true)
]
