webhook_url = ENV['DISCORD_WEBHOOK_URL']

desc "Build for testing"
lane :build_for_testing do
  cocoapods
  scan(
    build_for_testing: true
  )
end

desc "Run tests"
lane :run_ChatApp_tests do
  scan(
    test_without_building: true
  )
end

desc "Send notification to Discord"
lane :discord_notification do
  client = Discordrb::Webhooks::Client.new(url: webhook_url)
  client.execute do |builder|
    builder.add_embed do |embed|
      embed.title = "ChatApp"
      embed.colour = 0x4BB543
      embed.description = "Success"
      embed.author = Discordrb::Webhooks::EmbedAuthor.new(
        name: "Alexander Saushev")
      embed.timestamp = Time.now
    end
  end
end

desc "Build, run tests and notify"
lane :build_and_test do
  build_for_testing
  run_ChatApp_tests
  discord_notification
end